const MODES = {
	EXIT: 0,
	IMPORT: 1,
	APPLICATION: 2,
	MANAGEMENT: 3,
	EXPORT: 4
}

const MANAGEMENT_MODES = {
	RETURN: 0,
	MANAGE_PLAYERS: 1,//MUST
	MANAGE_GAMES: 2, //MUST
	PLAN_GAMENIGHT: 3 //MUST
}

const MANAGEMENT_PLAYERS_MODES = {
	RETURN: 0,
	ADD: 1, //MUST
	EDIT: 2, //NICETOHAVE
	DELETE: 3 //MUST
}

const EDIT_PLAYERS = {
	RETURN: 0,
	NAME: 1,
	GAME: 2
}

const MANAGEMENT_GAMES_MODES = {
  RETURN: 0,
  ADD: 1, //MUST
  EDIT: 2, //NICETOHAVE
  DELETE: 3 //MUST
}

const DELETE_GAME = {
	RETURN: 0,
	GLOBAL: 1,
	PLAYER: 2
}

const MENUES = {
	MAIN: 0,
	MANAGEMENT: 1,
	PLAYER_MANAGEMENT: {
		MENU: 2.0,
		EDIT_PLAYER: 2.1,
		DELETE_PLAYER: 2.2,
		ADD_PLAYER: 2.3,
	},
	GAME_MANAGEMENT: {
		MENU: 3.0,
		EDIT_PLAYER: 3.1,
		DELETE_PLAYER: 3.2,
		ADD_PLAYER: 3.3,
	},
	APPLICATION: 2,
	
	
}

exports.MODES = MODES;
exports.MANAGEMENT_MODES = MANAGEMENT_MODES
exports.MANAGEMENT_PLAYERS_MODES = MANAGEMENT_PLAYERS_MODES
exports.EDIT_PLAYERS = EDIT_PLAYERS
exports.MANAGEMENT_GAMES_MODES = MANAGEMENT_GAMES_MODES
exports.DELETE_GAME = DELETE_GAME
exports.MENUES = MENUES